version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8.2
    working_directory: ~/work
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.8/site-packages
      - restore_cache:
          key: deps9-{{ .Branch }}-{{ checksum "poetry.lock" }}
      - run:
          name: install dependencies
          command: |
            pip install poetry
            poetry install
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "poetry.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.8/site-packages"
      - persist_to_workspace:
          root: /home/circleci/work
          paths:
            - work
            - .cache/pypoetry
  test:
    docker:
      - image: circleci/python:3.8.2
    working_directory: ~/work
    steps:
      - attach_workspace:
          at: /home/circleci/work
      - run:
          command: |
            poetry
            poetry show
            poetry build
            poetry shell
            pytest

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
