version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8.2
    working_directory: ~/42cli
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.8/site-packages
      - restore_cache:
          key: deps9-{{ .Branch }}-{{ checksum "poetry.lock" }}
      - run:
          name: install dependencies
          command: |
            pip install poetry
            poetry install
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "poetry.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.8/site-packages"
      - persist_to_workspace:
          root: /home/circleci/42cli
          paths:
            - .
  test:
    docker:
      - image: circleci/python:3.8.2
    working_directory: ~/42cli
    steps:
      - attach_workspace:
          at: /home/circleci/42cli
      - run:
          command:
            poetry run pytest

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
