version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5

jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.8.2
    working_directory: ~/work
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.8/site-packages
      - restore_cache:
          key: deps9-{{ .Branch }}-{{ checksum "poetry.lock" }}
      - run:
          name: install dependencies
          command: |
            pip install poetry
            poetry install
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "poetry.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.8/site-packages"
      - run:
          command: |
            poetry run pytest -v --cov=42cli --cov-report=xml
      - codecov/upload:
          file: coverage.xml

workflows:
  build_and_test:
    jobs:
      - build-and-test
